### ISSUE TITLE
ThaiProgrammer/tech-events-calendar project

### ISSUE THREAD

**Issue by dtinth** [unnawut/awesome-thai-dev#1]
Thanks for a great project!

I would like to suggest an addition of the repo [ThaiProgrammer/tech-events-calendar](https://github.com/ThaiProgrammer/tech-events-calendar) to the list. It is a project that aims to list the tech events that are relevant to people in Thailand.

I think it would be great if you could add this to the project to the list, as I think networking and meetups are great ways for developers to improve their skills and learn from each other.

(I am opening an issue instead of a PR, because I am not sure which section to put this link in. Thanks for understanding.)

**Comment by unnawut** [comment]
Ah thanks krub Thai. Added!

I wish your suggestion gets a bit more visibility, but for now I suppose it goes into "เว็บไซต์/บล็อก/ฯลฯ". I hope you don't mind. Will separate it when the list gets a bit longer.

Thanks again!

**Comment by dtinth** [comment]
Sounds great, thanks!!

**Comment by unnawut** [comment]
Now that there're a lot more events in the repo and much more actively maintained, I've bumped your suggestion up to top since building a stronger Thai dev community probably should be of a high, if not the highest, importance.

**Comment by dtinth** [comment]
Thanks a lot!
